# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "aula_2" ]
  pull_request:
    branches: [ "aula_2" ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        go_version: ['1.18', '1.17','>=1.18']
        os: [ubuntu-latest,windows-2022]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}
 
    - name: Build-DB
      run: docker-compose build
      
    - name: Create-DB
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go
    
  build:
   needs: test
   runs-on:  ${{ matrix.os }}
   strategy: 
      matrix:
        go_version: ['1.18', '1.17','>=1.18']
        os: [ubuntu-latest,windows-2022]
   steps:
      - uses: actions/checkout@v4
      - name: Build
        run: go build -v main.go
